### PR TITLE
added pcre-8.43

### PR DESCRIPTION
**Pull request by dillera**
Required DIDBS.

How can we start to incorporate didbs gcc into irix ports without it being a mess?

### CODE REVIEW

**Comment by larb0b** [comment]
We need a tardist of the toolchain, then we can replace the current one with it.

**Comment by dillera** [comment]
What about another elseif block to handle didbs paths?

**Comment by larb0b** [comment]
Since irixports is supposed to work on a fresh-ish IRIX install, it doesn't make sense to have some ports to rely on something that isn't bootstrapped.

**Comment by dillera** [comment]
i am hoping that irixports can continue to work on a fresh irix install with it's current toolchain, but that isn't the only mode it can operate in.

If the buildtools=xxx it simply won't execute if you don't have the proper build tools defined. 

If that is not a direction you want to go in, I can understand that and you can just close this PR.

**Comment by larb0b** [comment]
Well I don't see any reason someone couldn't build gcc with the didbs patches and then make a tardist either! https://www.youtube.com/watch?v=uVjRe8QXFHY

**Pull request closed without merging**
